# -*- coding: utf-8 -*-
"""Bootcamp_Week1_Day4_updated_requirements (2) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJAbx7P-UhdcaEer003wzKOXFnbpekhP

# Week 1 - Day 4 Lab: Automation Scripting & Mini Project
Today, you will practice writing structured Python scripts that automate data processing tasks using the same weather dataset.

**Objective**: Build a script that loads, processes, and outputs summaries from the dataset.

## Step 1: Create Project Structure
Create a new folder with the following structure:
```
weather_project/
├── data/
│   └── hourly_weather_10_days.csv
├── scripts/
│   ├── __init__.py
│   └── summary.py
├── output/
│   └── results.txt
└── main.py
```

## Step 2: Plan Your Script
- `main.py` will be the entry point
- `summary.py` will contain helper functions to:
  - Load data
  - Clean missing values
  - Compute summaries (mean, min, max)
  - Save results

## Step 3: Write Summary Functions
Create and test the following functions in `summary.py`:
- `load_data(filepath)`
- `clean_data(df)`
- `compute_summary(df)` → returns dictionary
- `save_summary(summary_dict, output_path)`
"""

import pandas as pd
import numpy as np

path =  "/content/hourly_weather_10_days (1).csv"

df = pd.read_csv(path)
df.head()

def load_data(filepath):

  df = pd.read_csv(filepath)
  return df



def clean_data(df):

  df.dropna(inplace=True)
  return df

def summary(df):
  summary_df = df.describe
  summary_dict = summary_df.to_dict()
  return summary_dict

def save_summary(summary, output_path):

    with open(output_path, 'w') as file:
        for col, stats in summary.items():
            file.write(f"{col}:\n")
            for stat, value in stats.items():
                file.write(f"  {stat}: {value}\n")
                file.write("\n")

"""## Step 4: Use `main.py` to Control Execution
- Use `argparse` to pass file paths via command line
- Call your functions in a logical order
"""

# Placeholder example: main.py


# Workflow
# 1. Load dataimport
# 2. Clean data
# 3. Compute summary
# 4. Save output

"""## Final Submission Checklist
- [ ] Folder structured correctly
- [ ] Script runs end-to-end from CLI
- [ ] Code is modular and commented
- [ ] Output file is saved with correct values
- [ ] Bonus features (optional)
"""