# -*- coding: utf-8 -*-
"""day 2 notebooks (2) (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I6PD90QR1tHSTR_ee2J4z-cH2bxnwIiF
"""

print("Hello world")

name = 'Farah'
age =22
height = 5.5
is_student= True


print(type(name))
print(type(age))
print(type(height))
print(type(is_student))

score=int(input("Enter your Score(0-100): "))

if score >= 90:
  print("Grade:A")
elif score >= 80:
    print("Grade:B")
elif score >= 70:
    print("Grade:C")
elif score >= 60:
      print("Grade:D")
else:
        print("Grade:E")

n = 5 #height of triangle

for i in range(1, n+1):
  print ('*' * i)

squares = []

for x in range (1, 11):
  squares.append(x**2)
  print(squares)

sample_tuple = ('red', 'green' ,'blue', 'yellow', 'purple')

# set with add values
sample_set = set()
sample_set.add('apple')
sample_set.add('banana')

#Dictionary with key value pairs

sample_dict ={'name':'Farah Niazi', 'age':'22'}


# print results

print("Tuple:", sample_tuple )
print("Set:",sample_set)
print("Dictionary:", sample_dict)

text ="Python is simple yet powerful. Python is easy to learn."

# Remove dot and convert text to lowercase

text = text.replace('.' , '').lower()

words = text.split()

word_freq={}

# Count each word
for word in words:
  if word in word_freq:
      word_freq[word] += 1
  else:
        word_freq[word] = 1

        print(word_freq)

# Define the function outside the list definition
def modify_list(my_list):
    my_list.append("new item")  # Adding "new item" to the list

# Initial list
lst = ["item1", "item2"]

# Call the function and pass the list
modify_list(lst)

# Print the modified list
print(lst)